_core:
  default_config_hash: 9bVDfWSa_In6VzTXmy04jJ_3ZQobihKjO9isuuUCPaw
protect_all_forms: true
unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
log: false
element_name: url
time_limit: 2
expire: 120
form_settings:
  user_register_form: false
  user_pass: false
  contact_message_feedback_form: false
  contact_message_personal_form: false
  node_article_form: false
  node_event_form: false
  node_gallery_form: false
  node_location_form: false
  node_page_form: false
  node_portfolio_form: false
  node_service_form: false
  node_support_ticket_system_form: false
  node_team_form: false
  node_testimonial_form: false
  comment_comment_form: false
