features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://IT-Lasso-logo-3.png'
favicon:
  use_default: 1
theme_skin: ''
enable_customize: '1'
logo_width: 160px
logo_padding_top: ''
logo_padding_bottom: ''
sticky_menu: '1'
site_layout: wide
preloader: '0'
google_key: ''
default_header: header
footer_skin: ''
footer_first_size: '3'
footer_second_size: '3'
footer_third_size: '3'
footer_four_size: '3'
customize_css: ".header-one {\r\n  background: #000000;\r\n}\r\n@media (min-width: 1024.1px) {\r\n  .header-one .stuck {\r\n    background-image: linear-gradient(#000000, #FF851B);\r\n    box-shadow: 0 0 10px 4px rgb(0 0 0 / 87%);\r\n  }\r\n}\r\nheader .site-branding-logo {\r\n  padding: 0px 0 0px;\r\n  display: inline-block;\r\n  height: auto;\r\n}\r\n.topbar__one {\r\n  border-bottom: 1px solid #000000;\r\n}\r\n.el-81131057 {\r\n    background: transparent linear-gradient(291deg, #dddddd 0%, #134346 74%, #134346 100%) 0% 0% no-repeat padding-box;\r\n}\r\n.el-81131057 > .bb-inner {\r\n  padding-top: 0px;\r\n  padding-bottom: 0px;\r\n}\r\n.image text-center {\r\n  background-image: url(\"img src=\"/sites/default/files/intro-img.png\" alt=\"IT Lasso Overview\");\r\n}\r\n.iconbox-one__single {\r\n  margin-bottom: 20px;\r\n}\r\nh1, .h1 {\r\n  font-size: calc(1.325rem + 0.9vw);\r\n  color: #008080 !important;\r\n}\r\n.services-slider-height {\r\n  height: 300px !important;\r\n}\r\n#block-notech-subtheme-websitedevelopmentquestionnaire {\r\n  height: 600px;\r\n}\r\nh2.gsc-heading__title{\r\n  color: #008080 !important;\r\n}\r\n.panel .panel-heading .panel-title {\r\n  font-size: 18px;\r\n  background-color: #008080 !important;\r\n  padding: 0 10px 0 10px !important;\r\n}\r\n.panel .panel-heading {\r\n  background: none !important;\r\n  padding: 0 !important;\r\n  margin-bottom: 0;\r\n  background-color: #008080 !important;\r\n}"
header_info: "<div class=\"header-call__wrapper\">\r\n\t<div class=\"header-call__icon\">\r\n\t\t<img src=\"https://gaviasthemes.net/drupal/notech/themes/custom/notech/assets/images/comment-icon.png\" alt=\"\">\r\n\t</div>\r\n\t<div class=\"header-call__content\">\r\n                  <p>Need help? Talk to an expert </p>\r\n                  <h5><a href=\"tel:+980009850\"><span>Free</span> +98 (000)-9850</a></h5>\r\n           </div>\r\n</div>"
